name: App
run-name: ${{ github.actor }} is deploy App Mobile ðŸš€
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Bucket-Deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'deploy'
        uses: 'bitovi/github-actions-gcp-bucket'
        with:
          gcp_access_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          bucket_name: abc-jobs-apk
          file_name: pubspec.lock